name: medicare_plus
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.4.1
  firebase_auth: ^3.5.1
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_custom_clippers: ^2.0.0
  flutter_localizations:
    sdk: flutter
  google_nav_bar: ^5.0.6
  intl: ^0.17.0
  lottie: ^1.3.0
  percent_indicator: ^4.2.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
